from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn
from .mock_llm import MockCloudLLM, MockLocalLLM
from .mock_github import MockGitHubClient

console = Console()

class MockRunner:
    def __init__(self):
        self.cloud = MockCloudLLM()
        self.local = MockLocalLLM()
        self.github = MockGitHubClient()

    def show_status(self):
        table = Table(title="🤖 AI Assistant Status (MOCK)")
        table.add_column("Component", style="cyan"); table.add_column("Status", style="green")
        table.add_row("Cloud LLM", "✅ Active"); table.add_row("Local LLM", "✅ Active")
        table.add_row("GitHub", "✅ Ready"); table.add_row("Web Server", "✅ Ready")
        console.print(table)

    def run_generation(self, prompt, use_cloud=True):
        llm = self.cloud if use_cloud else self.local
        name = "Cloud" if use_cloud else "Local"
        with Progress(SpinnerColumn(), TextColumn("[bold blue]Thinking...")) as progress:
            progress.add_task("gen", total=None)
            code = llm.generate(prompt)
        console.print(Panel(code, title=f"💻 Generated by {name}"))
        if console.input("\nPush to GitHub? (y/n): ").lower() == 'y':
            if not self.github.authenticated: self.github.login()
            self.github.push_file("test.py", code, "update")
            console.print("[green]✅ Pushed![/green]")

    def run_interactive(self):
        console.print("[bold]Interactive Mode[/bold] (type 'quit' to exit)")
        while True:
            p = console.input("\n👉 You: ")
            if p.lower() == 'quit': break
            self.run_generation(p)
